// 09vue/component-communication/src/App.vue
<template>
  <div id="app">
    <!-- <user-control></user-control> -->
  <student-vue></student-vue>
  </div>
</template>

<script>
import StudentVue from './views/Student/Student.vue'
import UserControl from './views/UserControl/UserControl.vue'

export default {
  name: 'app',
  components: {
    UserControl,
    StudentVue,
  }
}
</script>

<style>
</style>

// 10react/react-demo1/src/App.js
import React from 'react'
// import AntdComp from './components/AntdComp'
// import TodoList from './components/TodoList'
import Login from './views/Login'

export default function App() {

  return (
    <div>
      {/* <AntdComp></AntdComp> */}
      {/* <TodoList></TodoList> */}
      <Login></Login>
    </div>
  )
}
